name: Main
on:
  push:
    branches:
      - main
    tags:
      - baloney*
  issue_comment:
    types:
      - created

jobs:
  random-job:
    runs-on: ubuntu-latest
    name: main job
    steps:
      - name: echo
        run: echo this is the way
