name: Main
on:
  push:
    branches:
      - main
    tags:
      - baloney*
  issue_comment:
    types:
      - created

jobs:
  feedback-link:
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy now'
    runs-on: ubuntu-latest
    steps:
      - name: Feedback link
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[Workflow started! 🚀](https://github.com/studuffy-moia/actionz/actions/runs/${{ github.run_id }})`,
            });
  get-pr-sha:
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy now'
    runs-on: ubuntu-latest
    outputs:
      pr_sha: ${{ steps.sha.outputs.result }}
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      # - name: Export PR SHA
      #   run: echo "PR_SHA=${{ steps.sha.outputs.result }}" >> $GITHUB_ENV
  random-job:
    runs-on: ubuntu-latest
    needs: [get-pr-sha]
    name: main job
    steps:
      - name: echo
        run: echo this is the way
      - name: echo
        run: echo ${{ needs.get-pr-sha.outputs.pr_sha }}
  run-action:
    runs-on: ubuntu-latest
    needs: [get-pr-sha]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.get-pr-sha.outputs.pr_sha }}
      - uses: ./.github/actions/test
        with:
          who-to-greet: "stu"
