name: Main
on:
  push:
    branches:
      - main
    tags:
      - baloney*
  issue_comment:
    types:
      - created

jobs:
  get-pr-sha:
    if: github.event.issue.pull_request && github.event.comment.body == 'deploy now'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - name: Export PR SHA
        run: echo "PR_SHA=${{ steps.sha.outputs.result }}" >> $GITHUB_ENV
  random-job:
    runs-on: ubuntu-latest
    name: main job
    steps:
      - name: echo
        run: echo this is the way
      - name: echo
        run: echo ${{ env.PR_SHA }}
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.PR_SHA }}
      - uses: ./.github/actions/test
        with:
          who-to-greet: "stu"
